[project]
name = "shafu-formatter"
version = "0.1.0"
description = "A simple Solidity formatter"
requires-python = ">=3.8"
dependencies = [
    "tree-sitter-solidity>=0.0.2",
    "tree-sitter>=0.21.3",
]

[project.scripts]
shafu = "main:main" 
